<!----<p align="justify" style="margin-left:0"> <strong>Kebijakan privasi</strong><br />
  Halaman ini menjelaskan bagaimana data pribadi pengguna situs ini ditangani.&nbsp;Kebijakan privasi ini disediakan berdasarkan dekrit hukum 196/2003 pasal 13 (perlindungan data pribadi) bagi pengguna yang berinteraksi dengan layanan web secara online melalui <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a>. Kebijakan ini hanya mengacu pada <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a> situs dan tidak ke situs lain dimana pengguna dapat mengaksesnya melalui link yang ada di website ini. Pengguna yang mengunjungi <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a> secara implisit menerima ketentuan yang dijelaskan dalam kebijakan privasi ini. <br />
  <br />
  <span title="The data processing &ldquo;incumbent&rdquo;"><strong>Pengolahan data bagi &quot;yang berkepentingan &quot;</strong><br />
  </span><span title="Data referring to identified or identifiable persons may be processed following consultation of this site.">Data yang diolah ada data yang didapatkan dari para pengguna website ini.&nbsp;</span><span title="The 'incumbent' of such processing is MODENA.">&quot;Yang berkepentingan&quot; dari pemrosesan data tersebut adalah MODENA Indonesia.</span> <br />
  <br />
  <span title="Data processing location"><strong>Lokasi pengolahan data </strong><br />
  </span><span title="Processing connected with the web services provided by this site is carried out in the aforementioned incumbent's head office exclusively by the technical personnel in the incumbent company charged with such processing or persons engaged on an occasional basis for maintenance operations.">Pengolahan data yang didapatkan dari layanan website ini dilakukan di kantor pusat MODENA Indonesia, oleh tenaga teknis di perusahaan.&nbsp;</span><span title="No data deriving from the web service is communicated or made public.">Tidak ada data tersebut yang akan dikomunikasikan atau dipublikasikan.&nbsp;</span><span title="Personal data provided by users who request transmission of information or who register to receive newsletters are used for the sole purpose of providing the service requested.">Data pribadi yang diberikan oleh pengguna yang mendaftar untuk menerima newsletter digunakan untuk tujuan tunggal penyediaan layanan yang diminta oleh pengguna tersebut.</span> <br />
<br />
<span title="Navigation data"><strong>Navigasi Data</strong><br />
</span><span title="IT systems and software procedures used to operate this site acquire in the course of normal operation certain personal data, transmission of which is implicit in the use of Internet communication protocols.">Data diperolah dalam operasi website ataupun melalui pengiriman yang implisit dalam penggunaan protokol komunikasi Internet. D</span><span title="This category of data includes the IP addresses or domain names of the computers used by users connecting to the site, addresses in the URIs (Uniform Resource Identifier) of resources requested, time of request, method used to submit the request to the server, size">ata mencakup alamat IP atau nama domain dari komputer yang digunakan oleh pengguna, alamat di URI (Uniform Resource Identifier), waktu permintaan, metode yang digunakan untuk mengirimkan permintaan ke server, informasi </span><span title="of the file obtained in reply, numeric code indicating the state of the response given by the server (done, error, etc.) and other parameters relating to the user's operating system and IT environment."> file, kode numerik yang menunjukkan keadaan respon yang diberikan oleh server (error, dll) dan parameter lain yang berkaitan dengan sistem operasi pengguna dan lingkungan TI.&nbsp;</span><span title="These data are only used to obtain anonymous statistical information on the use of the site and to run operational checks and are cancelled immediately after processing.">Data-data ini hanya digunakan untuk mendapatkan informasi statistik anonim tentang penggunaan situs dan untuk menjalankan pemeriksaan operasional website.&nbsp;</span><span title="Data could be used to ascertain liability in the case of alleged computer crimes affecting this site.">Data dapat digunakan untuk memastikan kewajiban dalam kasus kejahatan komputer yang diduga mempengaruhi situs ini.</span> <br />
<br />
<span title="Data provided voluntarily by users">Data yang diberikan secara sukarela oleh pengguna<br />
</span><span title="Optional, explicit and voluntary sending of email to the addresses indicated in this site entails subsequent acquisition of the sender's address, which is needed to reply to requests, and of any other personal data included in the email.">Opsional, pengiriman eksplisit dan sukarela alamat email pengguna yang ditujukan ke pengelola situs ini, yang diperlukan untuk menjawab permintaan, dan data pribadi lain.&nbsp;</span><span title="Summary information on privacy will be indicated or displayed from time to time in the pages of the site referring to specific services on request.">Ringkasan informasi tentang privasi akan ditunjukkan atau ditampilkan dari waktu ke waktu dalam halaman situs merujuk ke layanan tertentu sesuai permintaan.</span> <br />
<br />
<span title="Optional supply of data"><strong>Opsional penyediaan data</strong><br />
</span><span title="Irrespective of the foregoing on navigation data, users are free to supply the personal data indicated in the request modules, or in any case indicated in the &ldquo;Contact us&rdquo; page, to request information material or other communications.">Terlepas dari sebelumnya pada data navigasi, pengguna bebas untuk memasok data pribadi yang ditujukan ke dalam modul permintaan, atau dalam hal yang disebutkan pada halaman &quot;Hubungi kami&quot;, untuk meminta materi informasi atau komunikasi lainnya.&nbsp;</span><span title="Failure to supply such data may mean it is impossible to obtain what has been requested.">Kegagalan untuk menyediakan data tersebut mungkin berarti tidak mungkin untuk mendapatkan apa yang telah diminta.</span> <br />
<br />
<span title="Processing methods"><strong>Pengolahan metode</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Data pribadi yang diproses oleh perangkat otomatis hanya untuk waktu yang benar-benar diperlukan untuk mencapai tujuan yang mereka dikumpulkan.&nbsp;</span><span title="Specific security measures are adopted to prevent loss, illicit or incorrect use of data and non authorized access thereto.">Langkah-langkah keamanan khusus yang diadopsi untuk mencegah kerugian, tidak sah atau penggunaan yang salah data dan tambahan akses non berwenang.</span> <br />
<br />
---->
<span title="Processing methods"><strong>PRIVACY STATEMENT</strong><br />
</span>
<p align="left" style="margin-left:0">
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">This privacy statement explains to you regarding our privacy activities and the choices you can make about how to collect information online and how such information shall be used. This statement shall apply only to MODENA's Website ("Website") and other software application ("App") that is owned and run by MODENA Indonesia, its subsidiaries and/or its affiliated companies ("MODENA").</span> <br />

<br>
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>1. Privacy Policy on the Website and App</strong></span>
<ol type="a"><span><li>MODENA shall collect your personal information including but not limited to name, address, electronic mail address and/or phone number you provide, change or add either online or at the time you register on the MODENA's Website and App. By providing your personal information, you agree to access and/or submit your personal information and give consent to its use for the benefit of MODENA.</li></span>
<span><li>MODENA may hand over personal information you provided to affiliated parties as well as other parties who cooperate with MODENA, including: (i) when it is required for the purpose of compliance with laws, regulations, court orders, (ii) upon request of the government, regulations or law enforcement agencies (iii) for the purpose of investigation and helping to prevent security threats, fraud or other misconduct (iv) to enforce/protect MODENA or its affiliated companies' rights and property or (v) to protect the rights or personal security of MODENA's employees and third parties.</li></span>
<span><li>You may update/add your personal information by logging in to MODENA's Website and App.</li></span>
<span><li>MODENA shall make reasonable efforts in managing your private information securely.</li></span>
<span><li>In complying with the laws and regulations, MODENA shall make continuous efforts to improve and take measures in protecting personal information.</li></span>
<span><li>If you are aged under 18, you are required to obtain your parent or guardian consent before submitting your personal information.</li></span>

</ol>
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>2. Links to non MODENA's Websites</span></strong>
<ol type="a"><span><li>This website and app provides links to third-party websites whose privacy practices may differ from MODENA privacy.</li></span>
<span><li>MODENA does not represent third-party websites. The personal information you provide to or collected by these third-party websites shall not be covered in this Privacy Statement. Before submitting personal information, you are required to read and understand the privacy policy of such third-party websites in advance.</li></span>
<span><li>This website and app may provide social media features allowing to share information and interact with MODENA by using your social networking account.</li></span>
<span><li>MODENA shall explicitly reject, to the extent permitted by laws, any responsibility for the security or privacy contained on or operated by third-party websites and social media.</li></span>
</ol>

<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>3. Changes to Privacy Statement</strong>
</span><br>
<span>We reserve the right to make changes to the privacy statement at any time, without prior notice.</span>






</p>
