<p align="left" style="margin-left:0"> <strong>SYARAT DAN KETENTUAN PENGGUNAAN SITUS MODENA </strong><br />
  Dengan mengakses, berselancar, atau menggunakan Situs MODENA ("Situs") ini, Anda dianggap mengetahui dan menerima syarat-syarat dan ketentuan-ketentuan dari MODENA Indonesia, anak perusahaannya dan/atau perusahaan afiliasinya ("MODENA") berikut ini: <br />
  <br />
  <!--<span title="The data processing &ldquo;incumbent&rdquo;"><strong>Pengolahan data bagi &quot;yang berkepentingan &quot;</strong><br />
  </span><span title="Data referring to identified or identifiable persons may be processed following consultation of this site.">Data yang diolah ada data yang didapatkan dari para pengguna website ini.&nbsp;</span><span title="The 'incumbent' of such processing is MODENA.">&quot;Yang berkepentingan&quot; dari pemrosesan data tersebut adalah MODENA Indonesia.</span> <br />
  <br />
  <span title="Data processing location"><strong>Lokasi pengolahan data </strong><br />
  </span><span title="Processing connected with the web services provided by this site is carried out in the aforementioned incumbent's head office exclusively by the technical personnel in the incumbent company charged with such processing or persons engaged on an occasional basis for maintenance operations.">Pengolahan data yang didapatkan dari layanan website ini dilakukan di kantor pusat MODENA Indonesia, oleh tenaga teknis di perusahaan.&nbsp;</span><span title="No data deriving from the web service is communicated or made public.">Tidak ada data tersebut yang akan dikomunikasikan atau dipublikasikan.&nbsp;</span><span title="Personal data provided by users who request transmission of information or who register to receive newsletters are used for the sole purpose of providing the service requested.">Data pribadi yang diberikan oleh pengguna yang mendaftar untuk menerima newsletter digunakan untuk tujuan tunggal penyediaan layanan yang diminta oleh pengguna tersebut.</span> <br />
<br />
<span title="Navigation data"><strong>Navigasi Data</strong><br />
</span><span title="IT systems and software procedures used to operate this site acquire in the course of normal operation certain personal data, transmission of which is implicit in the use of Internet communication protocols.">Data diperolah dalam operasi website ataupun melalui pengiriman yang implisit dalam penggunaan protokol komunikasi Internet. D</span><span title="This category of data includes the IP addresses or domain names of the computers used by users connecting to the site, addresses in the URIs (Uniform Resource Identifier) of resources requested, time of request, method used to submit the request to the server, size">ata mencakup alamat IP atau nama domain dari komputer yang digunakan oleh pengguna, alamat di URI (Uniform Resource Identifier), waktu permintaan, metode yang digunakan untuk mengirimkan permintaan ke server, informasi </span><span title="of the file obtained in reply, numeric code indicating the state of the response given by the server (done, error, etc.) and other parameters relating to the user's operating system and IT environment."> file, kode numerik yang menunjukkan keadaan respon yang diberikan oleh server (error, dll) dan parameter lain yang berkaitan dengan sistem operasi pengguna dan lingkungan TI.&nbsp;</span><span title="These data are only used to obtain anonymous statistical information on the use of the site and to run operational checks and are cancelled immediately after processing.">Data-data ini hanya digunakan untuk mendapatkan informasi statistik anonim tentang penggunaan situs dan untuk menjalankan pemeriksaan operasional website.&nbsp;</span><span title="Data could be used to ascertain liability in the case of alleged computer crimes affecting this site.">Data dapat digunakan untuk memastikan kewajiban dalam kasus kejahatan komputer yang diduga mempengaruhi situs ini.</span> <br />
<br />
<span title="Data provided voluntarily by users">Data yang diberikan secara sukarela oleh pengguna<br />
</span><span title="Optional, explicit and voluntary sending of email to the addresses indicated in this site entails subsequent acquisition of the sender's address, which is needed to reply to requests, and of any other personal data included in the email.">Opsional, pengiriman eksplisit dan sukarela alamat email pengguna yang ditujukan ke pengelola situs ini, yang diperlukan untuk menjawab permintaan, dan data pribadi lain.&nbsp;</span><span title="Summary information on privacy will be indicated or displayed from time to time in the pages of the site referring to specific services on request.">Ringkasan informasi tentang privasi akan ditunjukkan atau ditampilkan dari waktu ke waktu dalam halaman situs merujuk ke layanan tertentu sesuai permintaan.</span> <br />
<br />
<span title="Optional supply of data"><strong>Opsional penyediaan data</strong><br />
</span><span title="Irrespective of the foregoing on navigation data, users are free to supply the personal data indicated in the request modules, or in any case indicated in the &ldquo;Contact us&rdquo; page, to request information material or other communications.">Terlepas dari sebelumnya pada data navigasi, pengguna bebas untuk memasok data pribadi yang ditujukan ke dalam modul permintaan, atau dalam hal yang disebutkan pada halaman &quot;Hubungi kami&quot;, untuk meminta materi informasi atau komunikasi lainnya.&nbsp;</span><span title="Failure to supply such data may mean it is impossible to obtain what has been requested.">Kegagalan untuk menyediakan data tersebut mungkin berarti tidak mungkin untuk mendapatkan apa yang telah diminta.</span> <br />
<br />
<span title="Processing methods"><strong>Pengolahan metode</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Data pribadi yang diproses oleh perangkat otomatis hanya untuk waktu yang benar-benar diperlukan untuk mencapai tujuan yang mereka dikumpulkan.&nbsp;</span><span title="Specific security measures are adopted to prevent loss, illicit or incorrect use of data and non authorized access thereto.">Langkah-langkah keamanan khusus yang diadopsi untuk mencegah kerugian, tidak sah atau penggunaan yang salah data dan tambahan akses non berwenang.</span> <br />
<br />
<span title="Processing methods"><strong>PERNYATAAN PRIVASI</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Pernyataan privasi ini menerangkan kepada Anda mengenai kegiatan privasi kami dan pilihan yang dapat Anda buat mengenai cara mengumpulkan informasi secara daring dan bagaimana informasi tersebut digunakan. Pernyataan ini hanya berlaku pada Website MODENA ("Situs") yang dimiliki dan dijalankan oleh MODENA Indonesia, anak perusahaannya dan/atau perusahaan afiliasinya ("MODENA").</span> <br />
-->
<!--<ol type="1">-->
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>1. HUKUM DAN PERATURAN</strong></span><br />
<span>Akses dan penggunaan Situs ini tunduk pada hukum dan peraturan yang berlaku di Indonesia.
</span><br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>2. HAK CIPTA, MEREK DAN HAK KEKAYAAN INTELEKTUAL</strong></span><br />
<span>Merek, logo dan tanda layanan (seluruhnya, "Tanda") dan konten (termasuk namun tidak terbatas pada informasi, komunikasi, software, gambar, video dan suara) (seluruhnya, "Konten") yang terdapat pada atau tersedia pada Halaman Situs adalah milik, penyedia konten dan pemberi ijin pihak ketiga. Anda wajib menganggap bahwa seluruh Tanda dan Konten pada Halaman Situs dilindungi oleh hak cipta dan hak kekayaan intelektual yang berlaku kecuali ditentukan sebaliknya. Anda tidak dapat mereproduksi, mengubah, mengirimkan, membagikan, mempublikasikan, mengunduh atau menampilkan tanda dan konten dalam bentuk apapun atau dengan cara apapun termasuk namun tidak terbatas pada <em>electronic, mechanical photocopying</em> atau perekaman tanpa persetujuan tertulis terlebih dahulu dari kami. Anda setuju bahwa tanda dan konten yang terdapat dalam atau tersedia melalui Halaman Situs tidak dapat digunakan untuk tujuan komersial atau didistribusikan secara komersial. Setiap penggunaan yang tidak sah dari tanda atau konten dapat melanggar peraturan tentang hak cipta, merek, kerahasiaan dan publikasi dan peraturan pidana maupun perdata. Hak kami secara jelas terjaga. Jika Anda meyakini bahwa kekayaan intelektual Anda atau materi yang dilindungi hak cipta lainnya telah ditampilkan pada situs MODENA tanpa izin dari Anda, harap menginformasikan via surat elektronik: customercare@modena.co.id.
</span><br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>3. HYPERLINK</strong>
</span><br>
<span>SITUS INI MENYEDIAKAN TAUTAN KE SITUS LAIN UNTUK MENGAKSES MATERI PIHAK KETIGA ATAU DENGAN MEMBAWA MATERI PIHAK KETIGA KE DALAM SITUS INI MELALUI "INVERSE" HYPERLINKS DAN TEKNOLOGI FRAMING ("SITUS TERKAIT"). MODENA TIDAK MEMILIKI WEWENANG UNTUK MENGUBAH, MEMPERBAHARUI, ATAU MENGENDALIKAN ISI PADA SITUS TERKAIT. FAKTA BAHWA MODENA MENYEDIAKAN TAUTAN KE SEBUAH SITUS BUKAN MERUPAKAN DUKUNGAN, PENGESAHAN, SPONSOR, ATAU AFILIASI ATAS SITUS TERSEBUT, PEMILIKNYA, ATAU PENYEDIANYA. MODENA tidak bertanggung jawab atas penggunaan yang tidak selayaknya pada Situs dan framing setiap isi melalui Situs lainnya. Akses pada Situs Terkait adalah tanggung jawab Anda sendiri. Mohon untuk diketahui bahwa Situs Terkait dapat mengandung ketentuan dan peraturan, pernyataan privasi, ketentuan kerahasiaan, ketentuan transmisi data pribadi, dan ketentuan lain yang dapat berbeda dengan ketentuan-ketentuan yang ada pada Situs, dan MODENA tidak bertanggung jawab atas ketentuan tersebut serta secara tegas menolak segala tanggung jawab terkait dengan ketentuan-ketentuan tersebut.</span>
<br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>4. PEMBATASAN TANGGUNG JAWAB</strong>
</span><br />
<span>PRODUK YANG DITAMPILKAN DALAM KATALOG TUNDUK PADA PERUBAHAN TEKNIS, KETIDAKAKURATAN, KESALAHAN PENCETAKAN DAN KETERSEDIAAN. APABILA TERDAPAT INFORMASI ATAU HAL-HAL YANG TIDAK AKURAT ATAU KESALAHAN-KESALAHAN PENULISAN PADA SITUS ATAU SITUS TERKAIT, MODENA SECARA TEGAS MENOLAK BERTANGGUNG JAWAB ATAS KETIDAKAKURATAN ATAU KESALAHAN-KESALAHAN TERSEBUT. MODENA TIDAK MENJAMIN ATAU MENYATAKAN BAHWA ISI SITUS LENGKAP ATAU UP-TO-DATE. MODENA TIDAK BERKEWAJIBAN UNTUK MEMPERBAHARUI ISI SITUS. MODENA DAPAT MENGUBAH ISI YANG ADA PADA SITUS KAPANPUN TANPA PEMBERITAHUAN. ANDA MENYETUJUI BAHWA MODENA, PERUSAHAAN AFILIASINYA DAN PEJABATNYA, DIREKTUR, KARYAWAN, ATAU AGENNYA TIDAK AKAN BERTANGGUNG JAWAB, BAIK DALAM KONTRAK, TANGGUNG JAWAB HUKUM ATAU SEBALIKNYA, UNTUK SETIAP KERUSAKAN YANG LANGSUNG, DENDA, KHUSUS, KONSEKUENSIAL, INSIDENTAL ATAU TIDAK LANGSUNG (TERMASUK TETAPI TIDAK TERBATAS PADA HILANGNYA KEUNTUNGAN, BIAYA PENGGANTI MEMPEROLEH LAYANAN ATAU KEHILANGAN KESEMPATAN YANG TIMBUL DARI ATAU YANG BERHUBUNGAN DENGAN PENGGUNAAN SITUS ATAU SITUS TERKAIT, ATAU KETERLAMBATAN ATAU KETIDAKMAMPUAN MENGGUNAKAN SITUS ATAU SITUS TERKAIT, BAHKAN JIKA MODENA MENYADARI KEMUNGKINAN TERJADINYA KERUSAKAN TERSEBUT. PEMBATASAN TANGGUNG JAWAB INI TERMASUK TETAPI TIDAK TERBATAS PADA TIMBULNYA VIRUS YANG MUNGKIN DAPAT MERUSAK ALAT ANDA, KEGAGALAN MEKANIKAL ATAU ALAT ELEKTRONIK ATAU SALURAN KOMUNIKASI, TELEPON ATAU MASALAH KONEKSI INTERNAL LAINNYA SEPERTI KETIDAKMAMPUAN MENGAKSES LAYANAN INTERNET, AKSES YANG TIDAK SAH, PENCURIAN, KERUSAKAN OPERATOR, PEMOGOKAN ATAU MASALAH TENAGA KERJA LAINNYA ATAU SUATU KEADAAN MEMAKSA (FORCE MAJEURE). MODENA TIDAK DAPAT DAN TIDAK MENJAMIN AKSES KE SITUS YANG TERUS MENERUS, TIDAK TERGANGGU ATAU AMAN.</span>
<br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>5. KOMUNIKASI RAHASIA</strong>
</span><br>
<span>Kecuali diminta oleh petugas hukum dan berdasarkan Pernyataan Privasi MODENA, apabila Anda mengirimkan komunikasi atau materi apapun ke Situs dengan surat elektronik atau sebaliknya, termasuk data, pertanyaan, tanggapan, saran, atau sejenisnya, semua komunikasi tersebut adalah dan akan diperlakukan sebagai hal yang tidak rahasia dan tidak dimiliki pihak manapun.  Apapun yang Anda kirimkan akan digunakan oleh MODENA atau perusahaan afiliasinya untuk tujuan apapun, termasuk tetapi tidak terbatas pada, reproduksi, pengungkapan, pemindahan, publikasi, penyebaran, dan pengiriman. Selanjutnya, MODENA bebas menggunakan setiap ide, konsep, pengetahuan (know-how), atau teknik yang terdapat pada komunikasi apapun yang Anda kirimkan ke Situs untuk tujuan apapun, termasuk tetapi tidak terbatas pada pengembangan, manufaktur, dan pemasaran produk-produk menggunakan informasi tersebut, tanpa kompensasi atau ganti rugi apapun kepada Anda. MODENA tidak akan bertanggung jawab atas setiap interupsi yang tidak sah atau melanggar hukum atau modifikasi dari setiap komunikasi antara Anda dan MODENA (baik melalui surat elektronik atau sebaliknya), atau terhadap kehilangan, kerusakan yang timbul karenanya (termasuk tetapi tidak terbatas pada kehilangan, kerusakan yang timbul dari penggunaan informasi yang tidak sah atau penipuan yang menggunakan informasi yang terkandung dalam atau dibuat dapat diakses melalui komunikasi tersebut). Meskipun MODENA dari waktu ke waktu mengawasi atau memeriksa diskusi, pengiriman, perpindahan, forum, dan sejenisnya pada Situs, MODENA tidak berkewajiban untuk melakukannya dan tidak bertanggung jawab atas kewajiban yang timbul dari isi pada komunikasi tersebut maupun pada kesalahan, fitnah, pencemaran nama baik, hal tidak senonoh, atau ketidaktepatan yang terkandung dalam komunikasi tersebut. Anda dilarang untuk mengirimkan atau memindahkan materi yang melanggar hukum, mengancam, memfitnah, tidak senonoh, pornografi, atau materi apapun yang dapat mendorong tindakan yang akan dianggap suatu pelanggaran pidana atau menimbulkan tanggung jawab perdata, atau melanggar hukum. MODENA akan bekerjasama secara penuh dengan setiap pejabat penegak hukum atau perintah pengadilan yang meminta atau mengarahkan MODENA untuk mengungkapkan identitas dari siapapun yang mengirim materi tersebut.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>6. PEMINDAHAN DATA PRIBADI</strong>
</span><br>
<span>Anda dianggap telah membaca Pernyataan Privasi MODENA, memahaminya dan setuju bahwa dengan memberikan informasi pribadi atau kepemilikan kepada MODENA melalui Situs, Anda setuju bahwa informasi pribadi atau kepemilikan tersebut dapat berpindah atas perbatasan internasional yang diperlukan untuk pengolahan sesuai dengan standar praktik bisnis MODENA. Anda memahami bahwa Situs Terkait mungkin berisi ketentuan pengiriman data pribadi yang berbeda dari ketentuan yang tersedia di Situs MODENA. MODENA tidak bertanggung jawab atas ketentuan tersebut, dan menolak setiap dan semua kewajiban yang berkaitan dengan ketentuan tersebut.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>7. PEMBERITAHUAN KESADARAN PELANGGAN</strong>
</span><br>
<span>MODENA mengetahui akan adanya sejumlah surat elektronik penipuan yang dikirim ke masyarakat umum oleh pihak ketiga tanpa izin, dengan cara curang mengklaim akan menjalankan promosi. Contohnya termasuk surat elektronik yang dikirim tanpa diminta yang mengklaim bahwa penerima akan menerima donasi amal, memenangkan lotere atau penawaran pekerjaan. Kami menegaskan bahwa tidak ada dari surat elektronik semacam ini yang merupakan promosi MODENA yang resmi / penawaran pekerjaan dan dengan demikian kami tidak menerima adanya hubungan apapun dengan atau liabilitas yang timbul dari atau yang berkaitan dengan surat elektronik ini. Kami oleh karena itu menasihatkan agar penerima surat elektronik ini tidak merespons surat elektronik seperti itu dan/atau tidak memberikan data pribadi mereka.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>8. HUKUM YANG BERLAKU DAN YURISDIKSI</strong>
</span><br>
<span>Syarat dan Ketentuan ini diatur oleh dan ditafsirkan berdasarkan Hukum Negara Republik Indonesia.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>9. KETENTUAN UMUM</strong>
</span><br>
<span>Apabila salah satu dari Syarat dan Ketentuan Penggunaan ini menjadi tidak dapat dijalankan atau tidak berlaku, maka ketentuan yang tidak dapat dijalankan atau tidak berlaku akan dianggap digantikan dengan ketentuan yang sah dan dapat dijalankan yang paling mendekati ketentuan awal dan seluruh Syarat dan Ketentuan Penggunaan ini tetap berlaku. Kelalaian kami untuk menjalankan Syarat dan Ketentuan Penggunaan tidak dapat dianggap sebagai tindakan pengabaian suatu ketentuan atau hak.</span>
<!--</ol>-->





</p>
