<?

$arr_country=array(
"af"=>"Afghanistan",
"ax"=>"Aland Islands",
"al"=>"Albania",

"dz"=>"Algeria",
"as"=>"American Samoa",
"ad"=>"Andorra",
"ao"=>"Angola",
"ai"=>"Anguilla",
"aq"=>"Antarctica",

"ag"=>"Antigua and Barbuda",
"ar"=>"Argentina",
"am"=>"Armenia",
"aw"=>"Aruba",
"au"=>"Australia",
"at"=>"Austria",

"az"=>"Azerbaijan",
"bs"=>"Bahamas",
"bh"=>"Bahrain",
"bd"=>"Bangladesh",
"bb"=>"Barbados",
"by"=>"Belarus",

"be"=>"Belgium",
"bz"=>"Belize",
"bj"=>"Benin",
"bm"=>"Bermuda",
"bt"=>"Bhutan",
"bo"=>"Bolivia",

"ba"=>"Bosnia and Herzegovina",
"bw"=>"Botswana",
"bv"=>"Bouvet Island",
"br"=>"Brazil",
"io"=>"British Indian Ocean Territory",
"vg"=>"British Virgin Islands",

"bn"=>"Brunei",
"bg"=>"Bulgaria",
"bf"=>"Burkina Faso",
"bi"=>"Burundi",
"kh"=>"Cambodia",
"cm"=>"Cameroon",

"ca"=>"Canada",
"cv"=>"Cape Verde",
"ky"=>"Cayman Islands",
"cf"=>"Central African Republic",
"td"=>"Chad",
"cl"=>"Chile",

"cn"=>"China",
"cx"=>"Christmas Island",
"cc"=>"Cocos (Keeling) Islands",
"co"=>"Colombia",
"km"=>"Comoros",
"cg"=>"Congo",

"ck"=>"Cook Islands",
"cr"=>"Costa Rica",
"hr"=>"Croatia",
"cu"=>"Cuba",
"cy"=>"Cyprus",
"cz"=>"Czech Republic",

"cd"=>"Democratic Republic of Congo",
"dk"=>"Denmark",
"xx"=>"Disputed Territory",
"dj"=>"Djibouti",
"dm"=>"Dominica",
"do"=>"Dominican Republic",

"tl"=>"East Timor",
"ec"=>"Ecuador",
"eg"=>"Egypt",
"sv"=>"El Salvador",
"gq"=>"Equatorial Guinea",
"er"=>"Eritrea",

"ee"=>"Estonia",
"et"=>"Ethiopia",
"fk"=>"Falkland Islands",
"fo"=>"Faroe Islands",
"fm"=>"Federated States of Micronesia",
"fj"=>"Fiji",

"fi"=>"Finland",
"fr"=>"France",
"gf"=>"French Guyana",
"pf"=>"French Polynesia",
"tf"=>"French Southern Territories",
"ga"=>"Gabon",

"gm"=>"Gambia",
"ge"=>"Georgia",
"de"=>"Germany",
"gh"=>"Ghana",
"gi"=>"Gibraltar",
"gr"=>"Greece",

"gl"=>"Greenland",
"gd"=>"Grenada",
"gp"=>"Guadeloupe",
"gu"=>"Guam",
"gt"=>"Guatemala",
"gn"=>"Guinea",

"gw"=>"Guinea-Bissau",
"gy"=>"Guyana",
"ht"=>"Haiti",
"hm"=>"Heard Island and Mcdonald Islands",
"hn"=>"Honduras",
"hk"=>"Hong Kong",

"hu"=>"Hungary",
"is"=>"Iceland",
"in"=>"India",
"id"=>"Indonesia",
"ir"=>"Iran",
"iq"=>"Iraq",

"xe"=>"Iraq-Saudi Arabia Neutral Zone",
"ie"=>"Ireland",
"il"=>"Israel",
"it"=>"Italy",
"ci"=>"Ivory Coast",
"jm"=>"Jamaica",

"jp"=>"Japan",
"jo"=>"Jordan",
"kz"=>"Kazakhstan",
"ke"=>"Kenya",
"ki"=>"Kiribati",
"kw"=>"Kuwait",

"kg"=>"Kyrgyzstan",
"la"=>"Laos",
"lv"=>"Latvia",
"lb"=>"Lebanon",
"ls"=>"Lesotho",
"lr"=>"Liberia",

"ly"=>"Libya",
"li"=>"Liechtenstein",
"lt"=>"Lithuania",
"lu"=>"Luxembourg",
"mo"=>"Macau",
"mk"=>"Macedonia",

"mg"=>"Madagascar",
"mw"=>"Malawi",
"my"=>"Malaysia",
"mv"=>"Maldives",
"ml"=>"Mali",
"mt"=>"Malta",

"mh"=>"Marshall Islands",
"mq"=>"Martinique",
"mr"=>"Mauritania",
"mu"=>"Mauritius",
"yt"=>"Mayotte",
"mx"=>"Mexico",

"md"=>"Moldova",
"mc"=>"Monaco",
"mn"=>"Mongolia",
"ms"=>"Montserrat",
"ma"=>"Morocco",
"mz"=>"Mozambique",

"mm"=>"Myanmar",
"na"=>"Namibia",
"nr"=>"Nauru",
"np"=>"Nepal",
"nl"=>"Netherlands",
"an"=>"Netherlands Antilles",

"nc"=>"New Caledonia",
"nz"=>"New Zealand",
"ni"=>"Nicaragua",
"ne"=>"Niger",
"ng"=>"Nigeria",
"nu"=>"Niue",

"nf"=>"Norfolk Island",
"kp"=>"North Korea",
"mp"=>"Northern Mariana Islands",
"no"=>"Norway",
"om"=>"Oman",
"pk"=>"Pakistan",

"pw"=>"Palau",
"ps"=>"Palestinian Territories",
"pa"=>"Panama",
"pg"=>"Papua New Guinea",
"py"=>"Paraguay",
"pe"=>"Peru",

"ph"=>"Philippines",
"pn"=>"Pitcairn Islands",
"pl"=>"Poland",
"pt"=>"Portugal",
"pr"=>"Puerto Rico",
"qa"=>"Qatar",

"re"=>"Reunion",
"ro"=>"Romania",
"ru"=>"Russia",
"rw"=>"Rwanda",
"sh"=>"Saint Helena and Dependencies",
"kn"=>"Saint Kitts and Nevis",

"lc"=>"Saint Lucia",
"pm"=>"Saint Pierre and Miquelon",
"vc"=>"Saint Vincent and the Grenadines",
"ws"=>"Samoa",
"sm"=>"San Marino",
"st"=>"Sao Tome and Principe",

"sa"=>"Saudi Arabia",
"sn"=>"Senegal",
"sc"=>"Seychelles",
"sl"=>"Sierra Leone",
"sg"=>"Singapore",
"sk"=>"Slovakia",

"si"=>"Slovenia",
"sb"=>"Solomon Islands",
"so"=>"Somalia",
"za"=>"South Africa",
"gs"=>"South Georgia and South Sandwich Islands",
"kr"=>"South Korea",

"es"=>"Spain",
"pi"=>"Spratly Islands",
"lk"=>"Sri Lanka",
"sd"=>"Sudan",
"sr"=>"Suriname",
"sj"=>"Svalbard and Jan Mayen",

"sz"=>"Swaziland",
"se"=>"Sweden",
"ch"=>"Switzerland",
"sy"=>"Syria",
"tw"=>"Taiwan",
"tj"=>"Tajikistan",

"tz"=>"Tanzania",
"th"=>"Thailand",
"tg"=>"Togo",
"tk"=>"Tokelau",
"to"=>"Tonga",
"tt"=>"Trinidad and Tobago",

"tn"=>"Tunisia",
"tr"=>"Turkey",
"tm"=>"Turkmenistan",
"tc"=>"Turks And Caicos Islands",
"tv"=>"Tuvalu",
"ug"=>"Uganda",

"ua"=>"Ukraine",
"ae"=>"United Arab Emirates",
"uk"=>"United Kingdom",
"us"=>"United States",
"um"=>"United States Minor Outlying Islands",
"uy"=>"Uruguay",

"vi"=>"US Virgin Islands",
"uz"=>"Uzbekistan",
"vu"=>"Vanuatu",
"va"=>"Vatican City",
"ve"=>"Venezuela",
"vn"=>"Vietnam",

"wf"=>"Wallis and Futuna",
"eh"=>"Western Sahara",
"ye"=>"Yemen",
"zm"=>"Zambia",
"zw"=>"Zimbabwe",
"rs"=>"Serbia",

"me"=>"Montenegro",
);


?>
