<p align="left" style="margin-left:0"> <span style="font-weight: 800;">TERMS AND CONDITIONS OF USE OF MODENA'S WEBSITE </span><br />
  By accessing, surfing or using this MODENA's Website ("Website"), you are deemed to know and accept the following terms and conditions of MODENA Indonesia, its subsidiaries and/or its affiliated companies ("MODENA"):<br />
  <br />
  <!--<span title="The data processing &ldquo;incumbent&rdquo;"><strong>Pengolahan data bagi &quot;yang berkepentingan &quot;</strong><br />
  </span><span title="Data referring to identified or identifiable persons may be processed following consultation of this site.">Data yang diolah ada data yang didapatkan dari para pengguna website ini.&nbsp;</span><span title="The 'incumbent' of such processing is MODENA.">&quot;Yang berkepentingan&quot; dari pemrosesan data tersebut adalah MODENA Indonesia.</span> <br />
  <br />
  <span title="Data processing location"><strong>Lokasi pengolahan data </strong><br />
  </span><span title="Processing connected with the web services provided by this site is carried out in the aforementioned incumbent's head office exclusively by the technical personnel in the incumbent company charged with such processing or persons engaged on an occasional basis for maintenance operations.">Pengolahan data yang didapatkan dari layanan website ini dilakukan di kantor pusat MODENA Indonesia, oleh tenaga teknis di perusahaan.&nbsp;</span><span title="No data deriving from the web service is communicated or made public.">Tidak ada data tersebut yang akan dikomunikasikan atau dipublikasikan.&nbsp;</span><span title="Personal data provided by users who request transmission of information or who register to receive newsletters are used for the sole purpose of providing the service requested.">Data pribadi yang diberikan oleh pengguna yang mendaftar untuk menerima newsletter digunakan untuk tujuan tunggal penyediaan layanan yang diminta oleh pengguna tersebut.</span> <br />
<br />
<span title="Navigation data"><strong>Navigasi Data</strong><br />
</span><span title="IT systems and software procedures used to operate this site acquire in the course of normal operation certain personal data, transmission of which is implicit in the use of Internet communication protocols.">Data diperolah dalam operasi website ataupun melalui pengiriman yang implisit dalam penggunaan protokol komunikasi Internet. D</span><span title="This category of data includes the IP addresses or domain names of the computers used by users connecting to the site, addresses in the URIs (Uniform Resource Identifier) of resources requested, time of request, method used to submit the request to the server, size">ata mencakup alamat IP atau nama domain dari komputer yang digunakan oleh pengguna, alamat di URI (Uniform Resource Identifier), waktu permintaan, metode yang digunakan untuk mengirimkan permintaan ke server, informasi </span><span title="of the file obtained in reply, numeric code indicating the state of the response given by the server (done, error, etc.) and other parameters relating to the user's operating system and IT environment."> file, kode numerik yang menunjukkan keadaan respon yang diberikan oleh server (error, dll) dan parameter lain yang berkaitan dengan sistem operasi pengguna dan lingkungan TI.&nbsp;</span><span title="These data are only used to obtain anonymous statistical information on the use of the site and to run operational checks and are cancelled immediately after processing.">Data-data ini hanya digunakan untuk mendapatkan informasi statistik anonim tentang penggunaan situs dan untuk menjalankan pemeriksaan operasional website.&nbsp;</span><span title="Data could be used to ascertain liability in the case of alleged computer crimes affecting this site.">Data dapat digunakan untuk memastikan kewajiban dalam kasus kejahatan komputer yang diduga mempengaruhi situs ini.</span> <br />
<br />
<span title="Data provided voluntarily by users">Data yang diberikan secara sukarela oleh pengguna<br />
</span><span title="Optional, explicit and voluntary sending of email to the addresses indicated in this site entails subsequent acquisition of the sender's address, which is needed to reply to requests, and of any other personal data included in the email.">Opsional, pengiriman eksplisit dan sukarela alamat email pengguna yang ditujukan ke pengelola situs ini, yang diperlukan untuk menjawab permintaan, dan data pribadi lain.&nbsp;</span><span title="Summary information on privacy will be indicated or displayed from time to time in the pages of the site referring to specific services on request.">Ringkasan informasi tentang privasi akan ditunjukkan atau ditampilkan dari waktu ke waktu dalam halaman situs merujuk ke layanan tertentu sesuai permintaan.</span> <br />
<br />
<span title="Optional supply of data"><strong>Opsional penyediaan data</strong><br />
</span><span title="Irrespective of the foregoing on navigation data, users are free to supply the personal data indicated in the request modules, or in any case indicated in the &ldquo;Contact us&rdquo; page, to request information material or other communications.">Terlepas dari sebelumnya pada data navigasi, pengguna bebas untuk memasok data pribadi yang ditujukan ke dalam modul permintaan, atau dalam hal yang disebutkan pada halaman &quot;Hubungi kami&quot;, untuk meminta materi informasi atau komunikasi lainnya.&nbsp;</span><span title="Failure to supply such data may mean it is impossible to obtain what has been requested.">Kegagalan untuk menyediakan data tersebut mungkin berarti tidak mungkin untuk mendapatkan apa yang telah diminta.</span> <br />
<br />
<span title="Processing methods"><strong>Pengolahan metode</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Data pribadi yang diproses oleh perangkat otomatis hanya untuk waktu yang benar-benar diperlukan untuk mencapai tujuan yang mereka dikumpulkan.&nbsp;</span><span title="Specific security measures are adopted to prevent loss, illicit or incorrect use of data and non authorized access thereto.">Langkah-langkah keamanan khusus yang diadopsi untuk mencegah kerugian, tidak sah atau penggunaan yang salah data dan tambahan akses non berwenang.</span> <br />
<br />
<span title="Processing methods"><strong>PERNYATAAN PRIVASI</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Pernyataan privasi ini menerangkan kepada Anda mengenai kegiatan privasi kami dan pilihan yang dapat Anda buat mengenai cara mengumpulkan informasi secara daring dan bagaimana informasi tersebut digunakan. Pernyataan ini hanya berlaku pada Website MODENA ("Situs") yang dimiliki dan dijalankan oleh MODENA Indonesia, anak perusahaannya dan/atau perusahaan afiliasinya ("MODENA").</span> <br />
-->
<!--<ol type="1">-->
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>1. LAWS AND REGULATIONS</strong></span><br />
<span>Access and use of this Website are subject to the laws and regulations in Indonesia.
</span><br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>2. COPYRIGHT, TRADEMARKS AND INTELLECTUAL PROPERTY RIGHTS</strong></span><br />
<span>Trademarks, logos and service marks (entirely, "Mark") and the contents (including but not limited to information, communications, softwares, images, videos and sounds) (entirely, "Content") contained on or available on Web Pages are owned by third-party content providers and licensors. You shall assume that all Marks and Contents on Web Pages are protected by copyright and other applicable intellectual property rights unless otherwise specified. You shall not reproduce, modify, send, share, publish, download or display such marks and contents in any form or in any manner including but not limited to electronic, mechanical photocopying or recording without prior written consent from us. You shall agree that the marks and contents contained in or available through the Web Pages shall not be used for commercial purposes or being distributed commercially. Any unauthorized use of the marks or contents may violate regulations on copyright, trademark, confidentiality and publication, as well as civil and criminal laws. Our rights are explicitly retained. If you are convinced that your intellectual property or other copyrighted materials have been displayed on MODENA's website without your permission, please inform us via e-mail: customercare@modena.co.id.</span><br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>3. HYPERLINK</strong>
</span><br>
<span>THIS WEBSITE PROVIDES LINKS TO OTHER WEBSITES TO ACCESS THIRD-PARTY MATERIALS OR BY BRINGING THIRD-PARTY MATERIALS INTO THIS WEBSITE VIA “INVERSE” HYPERLINKS AND FRAMING TECHNOLOGY ("LINKED WEBSITES"). MODENA HAS NO AUTHORITY TO MODIFY, RENEW, OR CONTROL THE CONTENTS ON THE LINKED WEBSITES. THE FACT THAT MODENA PROVIDES A LINK TO A WEBSITE, IT DOES NOT CONSTITUTE A ENDORSEMENT, VALIDATION, SPONSORSHIP, OR AFFILIATION TO SUCH WEBSITE, ITS OWNER, OR ITS PROVIDER. MODENA shall not be liable for the improper use of the Website and framing of any contents through other Websites. Access to Linked Websites shall be at your own risk. Please note that Linked Websites may contain rules and regulations, privacy statements, confidentiality provisions, transmission of personal data provisions, and other provisions that may be different with the provisions contained on the Website, and MODENA shall not be liable for such provisions and expressly deny any liability associated with such provisions.</span>
<br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>4. LIMITATION OF LIABILITY</strong>
</span><br />
<span>PRODUCTS DISPLAYED IN CATALOGS ARE SUBJECT TO TECHNICAL CHANGES, INACCURACIES, PRINTING ERRORS AND AVAILABILITY. IN THE EVENT OF INACCURATE INFORMATION OR THINGS OR WRITING MISTAKES ON THE WEBSITE OR ANY LINKED WEBSITE, MODENA EXPRESSLY DISCLAIMS LIABILITY FOR SUCH INACCURACIES OR MISTAKES. MODENA DOES NOT GUARANTEE OR DECLARE THAT THE CONTENTS OF THE WEBSITE ARE COMPLETE OR UP-TO-DATE. MODENA SHALL NOT BE LIABLE TO RENEW THE CONTENTS OF THE WEBSITE. MODENA MAY CHANGE THE CONTENTS ON THE WEBSITE AT ANYTIME WITHOUT NOTICE. YOU SHALL AGREE THAT MODENA, ITS AFFILIATED COMPANIES AND ITS OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS SHAL NOT BE LIABLE, WHETHER IN CONTRACT, LEGAL LIABILITY OR OTHERWISE, FOR ANY DIRECT, PUNITIVE, PARTICULAR, CONSEQUENTIAL, INCIDENTAL OR INDIRECT DAMAGES (INCLUDING BUT NOT LIMITED TO LOST PROFITS, SUBSTITUTE COSTS OF OBTAINING SERVICES OR MISSED OPPORTUNITIES ARISING FROM OR IN CONNECTION WITH THE USE OF THE WEBSITE OR ANY LINKED WEBSITE, OR DELAY OR INABILITY TO USE THE WEBSITE OR ANY LINKED WEBSITE, EVEN IF MODENA IS AWARE OF THE POSSIBILITY OF SUCH DAMAGES. THIS LIMITATION OF LIABILITY INCLUDES BUT NOT LIMITED TO RISE OF VIRUSES THAT MAY DAMAGE YOUR DEVICES, MECHANICAL FAILURES OR FAILURES OF ELECTRONIC EQUIPMENTS OR COMMUNICATION LINES, TELEPHONE OR OTHER INTERNAL CONNECTION PROBLEMS SUCH AS INABILITY TO ACCESS INTERNET SERVICES, UNAUTHORIZED ACCESS, THEFT, OPERATOR DAMAGE, STRIKE OR OTHER LABOR PROBLEMS OR ANY FORCE MAJEURE. MODENA CANNOT AND DOES NOT GUARANTEE CONTINUOUS, UNINTERRUPTED OR SECURE ACCESS TO THE WEBSITE.</span>
<br>
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>5. CONFIDENTIAL COMMUNICATIONS</strong>
</span><br>
<span>Unless required by law enforcement officer and in compliance with MODENA's Privacy Statement, if you send any communications or materials to the Site by electronic mail or otherwise, including any data, questions, comments, suggestions, or the like, all such communications are, and will be treated as, non-confidential and non-proprietary. Anything you transmit or post shall be used by MODENA or its affiliated companies for any purpose, including, but not limited to, reproduction, disclosure, transmission, publication, broadcast, and posting. Furthermore, MODENA is free to use, without any compensation to you, any ideas, concepts, know-how, or techniques contained in any communication you send to the Site for any purpose whatsoever, including, but not limited to, developing, manufacturing, and marketing products using such information. MODENA shall not be held liable for any unauthorized or unlawful interruptions or modifications of any communications between you and MODENA (either by electronic mail or otherwise), or for any loss, damage inflicted (including but not limited to the loss, damage arising from unauthorized or fraudulent use of information using information contained in or made accessible through such communications). Although MODENA from time to time supervises or checks any discussions, posting, transmission, forums, and the like on the Site, MODENA shall be under no obligation to do so and shall not be responsible for the obligations arising from the contents in such communications or for any mistake, libel, defamation, profanity, or inaccuracy contained in such communications. You are prohibited to post or transmit any unlawful, threatening, defamatory, indecent, pornographic materials, or any materials that may encourage action that would be considered a criminal offense or give rise to civil liability or otherwise violate the law. MODENA shall fully cooperate with any law enforcement authorities or court orders requesting or directing MODENA to disclose the identity of anyone posting such materials.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>6. PERSONAL DATA TRANSMISSIONI</strong>
</span><br>
<span>You are deemed to have read the Privacy Statement of MODENA, understood and agreed that by providing personal or proprietary information to MODENA through the Website, you shall agree that such personal or proprietary information can be transferred over international borders required for processing in accordance with MODENA's business practice standards. You shall understand that the Linked Websites may contain provisions related to transmitting personal data that differ from the provisions provided on MODENA's Website. MODENA shall not be held liable for such provisions, and disclaim any and all liabilities related to such provisions.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>7. CUSTOMER AWARENESS NOTICE</strong>
</span><br>
<span>MODENA is aware of the existence of a number of fraudulent electronic mails sent to the public by a third party without permission, by fraudulently claiming to be running promotions. Examples may include electronic mail sent unsolicited claiming that the recipient will receive a charitable donation, wins the lottery or gets job offers. We affirm that there is no such kind of electronic mail considered being MODENA's official promotion/job offers and thus we shall not accept the existence of any relationship with or liability arising out of or relating to this electronic mail. We therefore advise that the recipient shall not respond to electronic mail as such and/or not provide their personal data.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>8. GOVERNING LAW AND JURISDICTION</strong>
</span><br>
<span>These terms and conditions are governed by and construed under the laws of the Republic of Indonesia.</span>
<br />
<br />
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>9. GENERAL PROVISIONS</strong>
</span><br>
<span>If any of these Terms and Conditions of Use shall become unenforceable or invalid, then such unenforceable or invalid condition shall be deemed superseded by a valid and unenforceable condition coming closest to the initial condition and all of the Terms and Conditions of Use shall remain in force. Our Negligence of executing the Terms and Conditions of Use shall not be regarded as an act neglecting any provision or right.</span>
<!--</ol>-->





</p>
