<!----<p align="justify" style="margin-left:0"> <strong>Kebijakan privasi</strong><br />
  Halaman ini menjelaskan bagaimana data pribadi pengguna situs ini ditangani.&nbsp;Kebijakan privasi ini disediakan berdasarkan dekrit hukum 196/2003 pasal 13 (perlindungan data pribadi) bagi pengguna yang berinteraksi dengan layanan web secara online melalui <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a>. Kebijakan ini hanya mengacu pada <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a> situs dan tidak ke situs lain dimana pengguna dapat mengaksesnya melalui link yang ada di website ini. Pengguna yang mengunjungi <a href="http://www.modena.co.id" class="link_white_nochange_hover_orange">www.modena.co.id</a> secara implisit menerima ketentuan yang dijelaskan dalam kebijakan privasi ini. <br />
  <br />
  <span title="The data processing &ldquo;incumbent&rdquo;"><strong>Pengolahan data bagi &quot;yang berkepentingan &quot;</strong><br />
  </span><span title="Data referring to identified or identifiable persons may be processed following consultation of this site.">Data yang diolah ada data yang didapatkan dari para pengguna website ini.&nbsp;</span><span title="The 'incumbent' of such processing is MODENA.">&quot;Yang berkepentingan&quot; dari pemrosesan data tersebut adalah MODENA Indonesia.</span> <br />
  <br />
  <span title="Data processing location"><strong>Lokasi pengolahan data </strong><br />
  </span><span title="Processing connected with the web services provided by this site is carried out in the aforementioned incumbent's head office exclusively by the technical personnel in the incumbent company charged with such processing or persons engaged on an occasional basis for maintenance operations.">Pengolahan data yang didapatkan dari layanan website ini dilakukan di kantor pusat MODENA Indonesia, oleh tenaga teknis di perusahaan.&nbsp;</span><span title="No data deriving from the web service is communicated or made public.">Tidak ada data tersebut yang akan dikomunikasikan atau dipublikasikan.&nbsp;</span><span title="Personal data provided by users who request transmission of information or who register to receive newsletters are used for the sole purpose of providing the service requested.">Data pribadi yang diberikan oleh pengguna yang mendaftar untuk menerima newsletter digunakan untuk tujuan tunggal penyediaan layanan yang diminta oleh pengguna tersebut.</span> <br />
<br />
<span title="Navigation data"><strong>Navigasi Data</strong><br />
</span><span title="IT systems and software procedures used to operate this site acquire in the course of normal operation certain personal data, transmission of which is implicit in the use of Internet communication protocols.">Data diperolah dalam operasi website ataupun melalui pengiriman yang implisit dalam penggunaan protokol komunikasi Internet. D</span><span title="This category of data includes the IP addresses or domain names of the computers used by users connecting to the site, addresses in the URIs (Uniform Resource Identifier) of resources requested, time of request, method used to submit the request to the server, size">ata mencakup alamat IP atau nama domain dari komputer yang digunakan oleh pengguna, alamat di URI (Uniform Resource Identifier), waktu permintaan, metode yang digunakan untuk mengirimkan permintaan ke server, informasi </span><span title="of the file obtained in reply, numeric code indicating the state of the response given by the server (done, error, etc.) and other parameters relating to the user's operating system and IT environment."> file, kode numerik yang menunjukkan keadaan respon yang diberikan oleh server (error, dll) dan parameter lain yang berkaitan dengan sistem operasi pengguna dan lingkungan TI.&nbsp;</span><span title="These data are only used to obtain anonymous statistical information on the use of the site and to run operational checks and are cancelled immediately after processing.">Data-data ini hanya digunakan untuk mendapatkan informasi statistik anonim tentang penggunaan situs dan untuk menjalankan pemeriksaan operasional website.&nbsp;</span><span title="Data could be used to ascertain liability in the case of alleged computer crimes affecting this site.">Data dapat digunakan untuk memastikan kewajiban dalam kasus kejahatan komputer yang diduga mempengaruhi situs ini.</span> <br />
<br />
<span title="Data provided voluntarily by users">Data yang diberikan secara sukarela oleh pengguna<br />
</span><span title="Optional, explicit and voluntary sending of email to the addresses indicated in this site entails subsequent acquisition of the sender's address, which is needed to reply to requests, and of any other personal data included in the email.">Opsional, pengiriman eksplisit dan sukarela alamat email pengguna yang ditujukan ke pengelola situs ini, yang diperlukan untuk menjawab permintaan, dan data pribadi lain.&nbsp;</span><span title="Summary information on privacy will be indicated or displayed from time to time in the pages of the site referring to specific services on request.">Ringkasan informasi tentang privasi akan ditunjukkan atau ditampilkan dari waktu ke waktu dalam halaman situs merujuk ke layanan tertentu sesuai permintaan.</span> <br />
<br />
<span title="Optional supply of data"><strong>Opsional penyediaan data</strong><br />
</span><span title="Irrespective of the foregoing on navigation data, users are free to supply the personal data indicated in the request modules, or in any case indicated in the &ldquo;Contact us&rdquo; page, to request information material or other communications.">Terlepas dari sebelumnya pada data navigasi, pengguna bebas untuk memasok data pribadi yang ditujukan ke dalam modul permintaan, atau dalam hal yang disebutkan pada halaman &quot;Hubungi kami&quot;, untuk meminta materi informasi atau komunikasi lainnya.&nbsp;</span><span title="Failure to supply such data may mean it is impossible to obtain what has been requested.">Kegagalan untuk menyediakan data tersebut mungkin berarti tidak mungkin untuk mendapatkan apa yang telah diminta.</span> <br />
<br />
<span title="Processing methods"><strong>Pengolahan metode</strong><br />
</span><span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Data pribadi yang diproses oleh perangkat otomatis hanya untuk waktu yang benar-benar diperlukan untuk mencapai tujuan yang mereka dikumpulkan.&nbsp;</span><span title="Specific security measures are adopted to prevent loss, illicit or incorrect use of data and non authorized access thereto.">Langkah-langkah keamanan khusus yang diadopsi untuk mencegah kerugian, tidak sah atau penggunaan yang salah data dan tambahan akses non berwenang.</span> <br />
<br />
---->
<span title="Processing methods"><strong>PERNYATAAN PRIVASI</strong><br />
</span>
<p align="left" style="margin-left:0">
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected.">Pernyataan privasi ini menerangkan kepada Anda mengenai kegiatan privasi kami dan pilihan yang dapat Anda buat mengenai cara mengumpulkan informasi secara daring dan bagaimana informasi tersebut digunakan. Pernyataan ini hanya berlaku pada Website MODENA ("Situs") dan aplikasi lain ("App") yang dimiliki dan dijalankan oleh MODENA Indonesia, anak perusahaannya dan/atau perusahaan afiliasinya ("MODENA").</span> <br />

<br>
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>1. Ketentuan Privasi pada Situs dan App</strong></span>
<ol type="a"><span><li>MODENA akan mengumpulkan informasi pribadi Anda termasuk tetapi tidak terbatas pada nama, alamat, alamat surat elektronik, dan/atau nomor telepon yang Anda berikan, ubah atau tambahkan baik secara daring atau pada saat Anda melakukan pendaftaran pada situs dan app MODENA. Dengan memberikan informasi pribadi Anda, Anda telah setuju untuk mengakses dan/atau menyerahkan informasi pribadi Anda dan menyetujui penggunaannya untuk kepentingan MODENA.</li></span>
<span><li>MODENA dapat memberikan informasi pribadi yang Anda berikan kepada pihak yang berafiliasi serta pihak-pihak lainnya yang bekerjasama dengan MODENA, termasuk: (i) bila hal tersebut diwajibkan untuk keperluan kepatuhan terhadap hukum, peraturan, perintah pengadilan, (ii) berdasarkan permintaan pemerintah, peraturan atau instansi penegak hukum (iii) untuk tujuan investigasi dan membantu untuk mencegah ancaman keamanan, penipuan atau tindakan kejahatan lainnya (iv) untuk menegakkan/melindungi hak dan properti dari MODENA atau perusahaan afiliasinya atau (v) untuk melindungi hak atau keamanan pribadi karyawan-karyawan MODENA dan pihak ketiga.</li></span>
<span><li>Anda dapat melakukan pengkinian/menambahkan informasi pribadi Anda dengan cara masuk ke Situs dan App MODENA.</li></span>
<span><li>MODENA akan melakukan upaya yang layak dalam mengelola informasi pribadi Anda secara aman.</li></span>
<span><li>Pada saat mematuhi hukum dan peraturan yang berlaku, MODENA akan melakukan upaya berkesinambungan untuk meningkatkan dan mengambil langkah dalam melindungi informasi pribadi</li></span>
<span><li>Apabila Anda berusia di bawah 18 tahun, maka Anda diminta untuk memperoleh persetujuan dari orang tua atau wali Anda sebelum menyerahkan informasi pribadi Anda.</li></span>
</ol>
<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>2. Tautan ke situs-situs non MODENA</span></strong>
<ol type="a"><span><li>Situs dan App ini menyediakan Tautan ke situs pihak ketiga yang praktik privasinya mungkin berbeda dengan privasi MODENA.</li></span>
<span><li>MODENA tidak mewakili situs pihak ketiga. Informasi pribadi yang Anda sediakan kepada atau dikumpulkan oleh situs pihak ketiga tersebut tidak tercakup pada Pernyataan Privasi ini. Sebelum menyerahkan informasi pribadi, Anda diminta untuk membaca dan memahami ketentuan privasi situs pihak ketiga tersebut terlebih dahulu.</li></span>
<span><li>Situs dan App ini dapat menyediakan fitur media sosial yang memungkinkan untuk berbagi informasi dan berinteraksi dengan MODENA dengan menggunakan akun jejaring sosial Anda.</li></span>
<span><li>MODENA secara tegas menolak, sejauh diizinkan oleh hukum, segala tanggung jawab terhadap keamanan atau privasi yang terdapat pada atau dioperasikan oleh situs pihak ketiga dan media sosial.</li></span>
</ol>

<span title="Personal data are processed by automatic devices only for the time strictly necessary to achieve the purposes for which they were collected."><strong>3. Perubahan terhadap Pernyataan Privasi</strong>
</span><br>
<span>Kami berhak melakukan perubahan terhadap pernyataan privasi sewaktu-waktu, tanpa pemberitahuan sebelumnya.</span>






</p>
